name: cli-jobs-pipelines-autom-mpg
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0/4 * * *"
  pull_request:
    branches:
      - main
      - sdk-preview
    paths:
      - jobs/autompg_pipeline/**
      - .github/workflows/cli-jobs-pipelines-auto-mpg-pipeline.yml
      - run-pipeline-jobs.sh
      - setup.sh
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Azure login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Setup environment
      run: bash setup.sh

    - name: Run job
      run: bash -x run-job.sh pipeline.yml
      working-directory: jobs/autompg_pipeline
